version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gofamily
      POSTGRES_DB: gofamily
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"

  service:
    build: .
    depends_on:
      - postgres